/* version.h -- Autogenerated! Do not edit. */

#ifndef __INCLUDE_NUTTX_VERSION_H
#define __INCLUDE_NUTTX_VERSION_H

#define CONFIG_VERSION_STRING "Unversioned"
#define CONFIG_VERSION_MAJOR 0
#define CONFIG_VERSION_MINOR 0
#define CONFIG_VERSION_BUILD "0"
#define CONFIG_GIT_REVISION_STR "nuttx-8.2-93-g736a0da+, master, taga-CFSZ5-3/taga, Fri 17-Apr-2020 09:46:53 JST"

#define CONFIG_VERSION ((CONFIG_VERSION_MAJOR << 8) | (CONFIG_VERSION_MINOR))

#endif /* __INCLUDE_NUTTX_VERSION_H */
